name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [main]         # change if your default branch is “master”
  workflow_dispatch:         # allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build      # “vite build” behind the scenes

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist          # Vite’s output dir
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
